services:
  postgresDB:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookeritosdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"